### ISSUE TITLE
Weird keycodes

### ISSUE THREAD

**Issue by Bios-Marcel** [Gibtnix/Apex-Macros#1]
Hey,

I don't think it works like it should, but I might be doing it wrong. I have the Apex 350 and am running Ubuntu 18.10.

The layer keys (`L1`-`L4`) are all recognized as  key `248`

For some of the `MX` keys, `xev` can't get any usable information at all, it just spits out this:
```
FocusOut event, serial 33, synthetic NO, window 0x4400001,
    mode NotifyUngrab, detail NotifyPointer

FocusIn event, serial 33, synthetic NO, window 0x4400001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 33, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
```

`M1` - `M8` are recognized as the usual utility keys you find on media keyboards (find, calculator ... blah blah blah). 

`M9`-`M12` are all recognized as `248`.

**Comment by Gibtnix** [comment]
Everything I can say that this seems to be perfectly normal. I'm also using an Apex 350 and it's exactly the same. I don't know if this can be fixed somehow. I did not find any possibility to map all keys to any arbitrary function as it's possible with the SteelSeries Engine on Windows.

**Comment by Bios-Marcel** [comment]
Oh, I see. I thought that this actually worked like on Windows. Thanks for the quick reply anyway.
