### ISSUE TITLE
Apex M800 support testing 

### ISSUE THREAD

**Issue by Mocktezuma** [Gibtnix/Apex-Macros#3]
Hello, I have the Apex M800 and im interesting in working with you to make it work if you're available. :)

**Comment by Gibtnix** [comment]
Hello, thanks for the offer, I'm very interested in trying to support the M800, too. I have created a different SteelSeries controller tool called [MSIKLM](https://github.com/Gibtnix/MSIKLM).
Please download it, compile it (installing is not required) by simply calling make. Then call

`sudo ./msiklm list`

to list up the available USB devices. The M800 should be detected and please post the respective output here. Then I can prepare a test program for the M800.

**Comment by Mocktezuma** [comment]
here is the output i got 
```
Device: SteelSeries Apex M800 Keyboard
    Device Vendor ID:        4152
    Device Product ID:       5632
    Device Serial Number:    (null)
    Device Manufacturer:     SteelSeries
    Device Path:             0001:0006:00
    Device Interface Number: 0
    Device Release Number:   519

Device: SteelSeries Apex M800 Keyboard
    Device Vendor ID:        4152
    Device Product ID:       5632
    Device Serial Number:    (null)
    Device Manufacturer:     SteelSeries
    Device Path:             0001:0006:01
    Device Interface Number: 1
    Device Release Number:   519

Device: SteelSeries Apex M800 Keyboard
    Device Vendor ID:        4152
    Device Product ID:       5632
    Device Serial Number:    (null)
    Device Manufacturer:     SteelSeries
    Device Path:             0001:0006:02
    Device Interface Number: 2
    Device Release Number:   519

Device: SteelSeries Apex M800 Keyboard
    Device Vendor ID:        4152
    Device Product ID:       5632
    Device Serial Number:    (null)
    Device Manufacturer:     SteelSeries
    Device Path:             0001:0006:03
    Device Interface Number: 3
    Device Release Number:   519
```

**Comment by Gibtnix** [comment]
[main.zip](https://github.com/Gibtnix/Apex-Macros/files/3741051/main.zip)

OK I've added a modified main.c file; you can check if it is working by downloading the current version from the repo and replace the main.c with the attached one.
But first of all, what happens if you start xev and press the macro keys? Are any events reported?
If no events are reported, compile the program and test it by calling 'sudo ./apex-macros enable'. The program will print "Keyboard found" if opening succeeds (which I expect to happen) and if so, then the macro keys should report keyboard events in xev. Good luck ;-)

**Comment by Mocktezuma** [comment]
this is the keycode I get when i launch ```xev | grep keycode : 
    state 0x0, keycode 172 (keysym 0x1008ff14, XF86AudioPlay), same_screen YES,
    state 0x0, keycode 172 (keysym 0x1008ff14, XF86AudioPlay), same_screen YES,
    state 0x0, keycode 174 (keysym 0x1008ff15, XF86AudioStop), same_screen YES,
    state 0x0, keycode 174 (keysym 0x1008ff15, XF86AudioStop), same_screen YES,
    state 0x0, keycode 173 (keysym 0x1008ff16, XF86AudioPrev), same_screen YES,
    state 0x0, keycode 173 (keysym 0x1008ff16, XF86AudioPrev), same_screen YES,
    state 0x0, keycode 171 (keysym 0x1008ff17, XF86AudioNext), same_screen YES,
    state 0x0, keycode 171 (keysym 0x1008ff17, XF86AudioNext), same_screen YES,
    state 0x0, keycode 169 (keysym 0x1008ff2c, XF86Eject), same_screen YES,
    state 0x0, keycode 169 (keysym 0x1008ff2c, XF86Eject), same_screen YES,```
I pressed from macro key 0 to 5, the 5 key doesnt send any keycode but increases the sound volume on my machine. (im using pulse audio). i will try to reinstall the program and give you a feedback.

**Comment by Mocktezuma** [comment]
update:
i could bind everythimg with xbindkey except for number 5, when i do xev on 5 it gives me this: 
```
FocusOut event, serial 31, synthetic NO, window 0x4200001,
    mode NotifyGrab, detail NotifyAncestor

FocusOut event, serial 31, synthetic NO, window 0x4200001,
    mode NotifyUngrab, detail NotifyPointer

FocusIn event, serial 31, synthetic NO, window 0x4200001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 31, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   ```

**Comment by Gibtnix** [comment]
Ok what exactly did you have to configure to get the macro keys working? Only enabling them by using the program or anything else? During my testing with the Apex 350 different macro keys triggered the same key events, i.e. maybe it is not possible to configure the keys in the same way as you could do running Windows. However, even if a few mappings are possible it is still worth using so I think I will add the change to the repo.

**Comment by Mocktezuma** [comment]
I retract my statement, it doesnt work anymore after a reboot. I will try to figurre out whats wrong

**Comment by Gibtnix** [comment]
That's perfectly normal, the keyboard will be reset after each reboot. You need to run the program once after every reboot, but there is an autostart functionality that automatically configures this (as long as your distro uses udev). Refer to the repo's main page for more information about this.

**Comment by Mocktezuma** [comment]
Closing this because my keyboard died and got replaced long ago...
