### ISSUE TITLE
Support for package managers other than apt

### ISSUE THREAD

**Issue by taep96** [Gibtnix/Apex-Macros#7]
Can't install on Arch because apt in not the package manager

**Comment by Gibtnix** [comment]
Actually, I'm not on Arch, so I can't test it by myself. The first option is to manually install the dependencies and compile the program, which should work finde. Besides this, I have an install script in another [repo](https://github.com/Gibtnix/MSIKLM/blob/master/install.sh), maybe you can try this one or replace the installation commands based on this script accordingly.
